#ShinyServerProject  ui.R

library(shiny)
shinyUI(pageWithSidebar(
    headerPanel("Calculate Advertising ROI"),
    
    sidebarPanel(
       numericInput(inputId = "TV", label = "Enter TV Budget in $000s",0),
       numericInput(inputId = "Radio", label = "Enter Radio Budget in $000s",0),
       numericInput(inputId = "MSRP", label = "Enter MSRP",0),
       numericInput(inputId = "Cost", label = "Enter Unit Cost", 0),
       submitButton('Submit')
         
        ),
        
    mainPanel(
        tabsetPanel(
            tabPanel("Output",
                     h4('Total advertising budget in 000s'),
                     verbatimTextOutput("outputValueB"),
                     h4('Expected Unit Sales in 000s'),
                     verbatimTextOutput("outputValueU"),
                     h4('Expected Revenue in 000s'),
                     verbatimTextOutput("outputValueR"),
                     h4('Expected ROI in 000s'),
                     verbatimTextOutput("outputValueP")
            ),
            tabPanel("Manual",
                     h3("Overview"),
                     p('This app estimates how many incremental units you
                            will sell based on your TV and Radio add spending.
                            '),
                     h3("How to use this app"),
                     p('Enter your advertising budget for TV and Radio
                         on the left. The numbers should be in thousands.
                         Enter your unit cost and retail price if you want the app
                        to calculate Total Revenue and ROI. Click submit.'),
                       p('Go to the Output tab to see the results'),
                     h3("How to interpret the results"),
                     h5('Total Avertising Budget:'),
                     p('This is the sum of the TV and Radio budgets you entered (in 000s).'),
                     h5('Expected Unit Sales:'),
                     p('This is the number of units (in 000s) you should 
                        expect to sell based on your advertising budget. 
                        If your advertising budget is $0 the prediction will be 3,000 units.
                       In other words without advertising the app predicts you will sell 3,000'),
                     h5('Expected Revenue:'),
                     p('Total Gross Revenue generated by the predicted units sales (units x MSRP).'),
                     h5('ROI:'),
                     p('Return on investment, calculated as: Expected Revenue - unit cost - 
                        total advertising budgt.'),
                     h3('Warning'),
                     p('The prediction function is a simple liner regression model
                        caclulated from the Advertising data in "An Introduction
                       to Statistical Learning". The data set is small and includes
                       only 4 predictors. In the real world many more factors impact
                       the effectiveness of an add campaign. So the predictions
                       shown here are only intended to demo the app. They will no
                       hold in the real world.')
                     )
            )
        )
    )

    )



